---
title: "About me"
output: 
  html_document:
    toc: true
    toc_float: true
---

## Resume/Curriculum Vitae


### EDUCATION	
**Columbia University Mailman School of Public Health**                                                
Masters of Public Health (Class of 2022) 

- Concentration: Biostatistics and Data Science 
- Certificate: Comparative Effectiveness and Outcomes Research

**University of Florida**		                                 
- Bachelor of Public Health(Class of 2020)	

**Relevant Coursework:** 
Statistical Computing with SAS, Analysis of Categorical Data, Relational Databases and SQL programming, Regression Analysis, Data Science I&II, Probability, Decision Analysis, Analysis of Large Datasets, Statistical Inference, Intro to Randomized Controlled Trials, Applied Methods-Outcomes Research, Genetics, Biochemistry

### RESEARCH			

**Principal Biostatistician**                                      
**Columbia Irving Medical Center – Vagelos College of Physicians** 
- Designed and managed data analysis as the principal biostatistician for a retrospective cohort study for Dr. Michael Mangold, Department of Psychiatry 
- Investigated the effect of drug use on the link between childhood trauma and later life cognition
      - Pulled and cleaned cognition data from the MIDUS national study database and conducted exploratory analysis to understand the association between childhood trauma and adult cognition
      - Conducted moderation analysis via regression analysis using linear/generalized mixed effect models in R
      - Presented research at annual Columbia Biostatistics Department Symposium

**Research Assistant**                                      
**Division for Nephrology, Hypertension at UF Health** 

- Reviewed and analyzed health data as a research assistant for Dr. Rajesh Mohandas, Department of Nephrology
- Investigated the long-term health complications of Catheter Related Blood Stream Infections and evaluated whether catheter salvage or exchange is associated with such complications
-	Reviewed medical records of patients diagnosed with CRBSI and interpreted whether the catheter practice used resulted in health complications
-	Conducted ANOVA analysis and univariate analysis of health data through Excel

**Research Assistant/Data Analyst**                                                                                        
**UF Health Center for Movement Disorders** 

- Computed and analyzed health data as a research assistant for Dr. Aparna Shukla, Department of Neurology 
- Investigated the characteristics of the tremor and dystonia in patients with progressive supranuclear palsy (PSP) and other atypical forms of Parkinson’s disease
-	Examined medical records of patients diagnosed with PSP and identified presence of tremor or dystonia that was then classified based on body distribution
-	Calculated a numerical analysis of patients that were identified with Tremor/Dystonia through excel
-	Presented research at the 71st American Academy of Neurology Annual Meeting

### PROFESSIONAL EXPERIENCE

**Monitor Support Tech**		              
**Internal Medicine Intensive Care Unit in UF Health/Shands**	

- Read and Monitored Electrocardiograms to identify instances of heart arrythmia or dysfunction
- Developed familiarity with accessing and inputting information in electronic health records in Epic

### SKILLS

**Software:** Microsoft Excel, SAS, mySQL, R, GitHub, STATA, MS Office(all advanced usage)

**Methods:** Linear and Multivariable Regression, ANOVA analysis, Logistic Regression and Model Building, Data Visualization and Tidying, Survival Analysis, Statistical Machine Learning, Propensity Score Analysis, Supervised and Unsupervised learning techniques

