---
title: "Plots"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    source: embed
---

```{r setup, include=FALSE}
library(tidyverse)
library(p8105.datasets)
library(plotly)

library(flexdashboard)
```

```{r warning = FALSE, include = FALSE}
data ("rest_inspec")

inspec_df =
  rest_inspec %>% 
  filter(
    boro == "MANHATTAN",
  ) %>% 
  distinct(dba,inspection_date, .keep_all= TRUE) %>% 
  drop_na(score)
```
Column {data-width=650}
-----------------------------------------------------------------------

###  Trends of Critical Violations by Year from 2013-2017 

```{r}
inspec_df %>% 
  separate(col = inspection_date, into = c("year", "month", "day"), sep ="-", remove = TRUE, convert = TRUE, extra = 'warn',fill='warn') %>% 
    mutate(
    month = 
      recode(month, 
             "1" = "January", "2" = "February",
             "3" = "March", "4" = "April",
             "5" = "May", "6" = "June",
             "7" = "July", "8" = "August",
             "9" = "September", "10" = "October",
             "11" = "November", "12" = "December")) %>%
  filter(
    critical_flag == "Critical") %>% 
  group_by(month,year) %>% 
  count(critical_flag) %>% 
  plot_ly(x=~month, y=~n, color = ~year, type="scatter") %>% 
  layout(
    title = "Number of Critical Violations over Time",
    xaxis= list(title= "Month"),
    yaxis= list(title="Number of Critical Violations")
  )
```

Column {data-width=350}
-----------------------------------------------------------------------

### Comparing Total Scores of Inspections with Critical vs Not Critical level violations

```{r}
inspec_df %>%
  filter(
    critical_flag %in% c("Critical","Not Critical")) %>% 
  plot_ly(y= ~score, color = ~critical_flag, type= "box", colors="viridis") %>% 
    layout(
      title = "Critical vs Not Critical Level Violations",
    xaxis= list(title= "Level of Violation"),
    yaxis= list(title="Total score of Inspection")
  )
```

### Frequency of Each Violation Code

```{r}
inspec_df %>% 
  count(violation_code) %>% 
  mutate(violation_code = fct_reorder(violation_code,n)) %>% 
  plot_ly(x= ~violation_code, y=~n,color= ~violation_code, type= "bar", colors="viridis") %>% 
    layout(
    title = "Frequency of Violation Code",
    xaxis= list(title= "Violation Code"),
    yaxis= list(title="Frequency of Violations")
  )
```

