---
title: "Other Projects"
output: 
  html_document:
    toc: true
    toc_float: true
    css: styles.css
---

## Phase III RCT Proposal

Download Proposal: [A Phase III Superiority Trial Proposal of CRISPR-Cas9 Gene Editing Therapy vs Hydroxyurea for Sickle Cell Disease Patients](CRISPR-Cas9 Phase III RCT Proposal.pdf)

Overview: I created a Phase III Randomized Control Trial Proposal where I designed a multicenter trial that answered the following clinical question: Among patients at least the age of 18 with sickle cell disease, is CRISPR-CAS-9 Therapy (single dose of CTX001 Infusion) superior to Hydroxyurea (15 milligram per kilogram of body weight) in reducing the frequency of Vaso-occlusive crises over the 2 years of individual follow-up? 


## Propensity Score Analysis 

Download Report: [Pyelonephritis Treatment: An Analysis of Outcomes between teaching & non-teaching hospitals](Applied Methods Final Project.pdf)

Overview: A study that utilizes a propensity score analysis using propensity score matching methods (Greedy 5:1) to investigate the impact of receiving treatment for pyelonephritis at a teaching hospital on length of stay and mortality. 

Software: SAS


## Effect of Concentrations of Various Major Air Pollutants on Cancer Prevalence at the State Level over Time

Link: [The Link Air Pollutant Concentration to Lung Cancer](https://arajann.github.io/finalproject.github.io/index.html)

Overview: A project that investigates the associations between major pollutant concentration levels and lung cancer at the population level with respect to time. Cancer statistics were retrieved from the American Cancer Society, and Air Pollution data in the US from 2000 to 2016 was gathered by the EPA. 

Software: RStudio


## Impact of Healthcare Access and HIV testing on utilization of Cervical Cancer Screening

Download: [Healthcare Access and HIV Testing on Cervical Cancer Screening](ar4173_jr4102 _final.pdf)

Overview: A replication study that looks at the impact of healthcare access and HIV testing on utilization of cervical cancer screening among US women at high risk of HIV infection. The original study was a cross-sectional analysis that utilized 2016 BRFSS data. 

Software: STATA